version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: deps
    groups:
      golang-x:
        patterns:
          - 'golang.org/x/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ci

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: docker
